- name: Check if flux installed
  stat:
    path: /usr/local/bin/flux
  register: flux_executable

- name: Download install script
  get_url:
    url: https://fluxcd.io/install.sh
    dest: /tmp/flux-install.sh
    mode: 0755
  when: not flux_executable.stat.exists

- name: Run install script
  shell:
    cmd: /tmp/flux-install.sh
    executable: /bin/bash
    creates: /usr/local/bin/flux
  become: true

- name: Delete install script
  file:
    path: /tmp/flux-install.sh
    state: absent

- name: Check if cluster bootstrapped with flux
  shell: kubectl get namespace flux-system
  register: flux_kubectl_namespace_exists
  ignore_errors: yes
  changed_when: false

- name: Run flux bootstrap
  shell: |
    flux bootstrap github \
    --owner={{ github_user }} \
    --repository={{ repository }} \
    --branch=main \
    --path=./clusters/{{ cluster }} \
    --personal
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  args:
    executable: /bin/bash
  when: flux_kubectl_namespace_exists.rc == 1
