- name: home-server
  hosts: pi

  vars:
    cluster: production
    github_user: cristianrgreco
    repository: home-server-flux-setup

  vars_prompt:
    - name: github_token
      prompt: Enter the GitHub token for Flux to bootstrap the cluster
      private: yes

  roles:
    - microk8s
    - kubeseal
    - flux
