- name: Install microk8s
  snap:
    name: microk8s
    classic: true
    state: present
  become: true

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes
  become: true

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: 0700

- name: Install kubectl
  snap:
    name: kubectl
    classic: true
    state: present
  become: true

# https://microk8s.io/docs/working-with-kubectl
- name: Generate microk8s config file
  shell: microk8s config > /home/{{ ansible_user }}/.kube/config
  args:
    executable: /bin/bash
    creates: /home/{{ ansible_user }}/.kube/config

- name: Enable metrics-server addon
  shell: microk8s enable metrics-server
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable hostpath-storage addon
  shell: microk8s enable hostpath-storage
  args:
    executable: /bin/bash
  changed_when: false
