- name: Check if kubeseal installed
  stat:
    path: /usr/local/bin/kubeseal
  register: kubeseal_executable

- name: Download archive
  get_url:
    url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ kubeseal_version }}/kubeseal-{{ kubeseal_version }}-linux-{{ kubeseal_arch }}.tar.gz
    dest: /tmp/kubeseal-{{ kubeseal_version }}-linux-{{ kubeseal_arch }}.tar.gz
  when: not kubeseal_executable.stat.exists

- name: Extract binary
  unarchive:
    src: /tmp/kubeseal-{{ kubeseal_version }}-linux-{{ kubeseal_arch }}.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: /tmp/kubeseal

- name: Install binary
  copy:
    src: /tmp/kubeseal
    dest: /usr/local/bin/kubeseal
    remote_src: yes
    mode: '0755'
  become: true

- name: Delete archive
  file:
    path: /tmp/kubeseal-{{ kubeseal_version }}-linux-{{ kubeseal_arch }}.tar.gz
    state: absent

- name: Check if public key exists
  stat:
    path: /home/{{ ansible_user }}/pub-sealed-secrets.pem
  register: public_key

- name: Save public key
  shell: |
    kubeseal --fetch-cert \
    --controller-name=sealed-secrets-controller \
    --controller-namespace=flux-system \
    > /home/{{ ansible_user }}/pub-sealed-secrets.pem
  args:
    executable: /bin/bash
  when: not public_key.stat.exists
